[package]
name = "caeli"
version = "0.1.0"
authors = ["Clément Sibille <clement.sibille@protonmail.com>"]
edition = "2018"

[dependencies]
tuber = { git = "https://github.com/tuber-engine/tuber.git", features = ["window", "sdl_window"]}
