[package]
name = "caeli"
version = "0.1.0"
authors = ["Clément SIBILLE <claymeuns@protonmail.com>"]
edition = "2018"

[dependencies]
tuber = { git = "https://github.com/Lisible/tuber.git" }
tuber_window_sdl2 = { git = "https://github.com/Lisible/tuber_window_sdl2.git" }
sdl2 = "0.32.1"
